# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
from time import time

start = time()
fib = [1, 2]

while True:
    sum_of_last_two = sum(fib[-2:])
    if sum_of_last_two >= 4e6:
        break
    fib.append(sum_of_last_two)

sum_of_even = sum([i for i in fib if i % 2 == 0])
print(f"{sum_of_even} in {time() - start} seconds")
